services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=library_db'
      - 'POSTGRES_PASSWORD=1234jhny'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'